In [4]:
import pandas as pd

In [5]:
# Import Data
df = pd.read_csv("Sample - Superstore.csv", encoding="windows-1252")
df #Display Data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [3]:
# Pengecekan Data Awal
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [4]:
# Check Missing Value
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [5]:
# Check Duplicate
df.duplicated().sum()

np.int64(0)

In [6]:
df[["Order Date", "Ship Date"]].head(30)

    Order Date   Ship Date
0    11/8/2016  11/11/2016
1    11/8/2016  11/11/2016
2    6/12/2016   6/16/2016
3   10/11/2015  10/18/2015
4   10/11/2015  10/18/2015
5     6/9/2014   6/14/2014
6     6/9/2014   6/14/2014
7     6/9/2014   6/14/2014
8     6/9/2014   6/14/2014
9     6/9/2014   6/14/2014
10    6/9/2014   6/14/2014
11    6/9/2014   6/14/2014
12   4/15/2017   4/20/2017
13   12/5/2016  12/10/2016
14  11/22/2015  11/26/2015
15  11/22/2015  11/26/2015
16  11/11/2014  11/18/2014
17   5/13/2014   5/15/2014
18   8/27/2014    9/1/2014
19   8/27/2014    9/1/2014
20   8/27/2014    9/1/2014
21   12/9/2016  12/13/2016
22   12/9/2016  12/13/2016
23   7/16/2017   7/18/2017
24   9/25/2015   9/30/2015
25   1/16/2016   1/20/2016
26   1/16/2016   1/20/2016
27   9/17/2015   9/21/2015
28   9/17/2015   9/21/2015
29   9/17/2015   9/21/2015

In [7]:
# Ubah Format Date
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%m/%d/%Y") 
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%m/%d/%Y")

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB

In [9]:
# Check unique values in categorical columns

print("Ship Mode:")
print(df["Ship Mode"].value_counts())

print("\nSegment:")
print(df["Segment"].value_counts())

print("\nRegion:")
print(df["Region"].value_counts())

print("\nCategory:")
print(df["Category"].value_counts())

print("\nSub-Category:")
print(df["Sub-Category"].value_counts())

Ship Mode:
Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

Segment:
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

Region:
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Category:
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

Sub-Category:
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [10]:
# Check numerical data distribution
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [11]:
# Check invalid numerical values
print("Sales <= 0:", (df["Sales"] <= 0).sum())
print("Quantity <= 0:", (df["Quantity"] <= 0).sum())
print("Discount < 0:", (df["Discount"] < 0).sum())
print("Discount > 1:", (df["Discount"] > 1).sum())

Sales <= 0: 0
Quantity <= 0: 0
Discount < 0: 0
Discount > 1: 0

In [12]:
# Check invalid shipping date
print("Ship Date before Order Date:",
      (df["Ship Date"] < df["Order Date"]).sum())

Ship Date before Order Date: 0

In [13]:
for col in ["Sales", "Profit"]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(col)
    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)
    print("Total Outlier:", len(outlier))
    print()

Sales
Lower Bound: -271.71000000000004
Upper Bound: 498.93
Total Outlier: 1167

Profit
Lower Bound: -39.724125
Upper Bound: 70.816875
Total Outlier: 1881

In [14]:
# Show transactions with the lowest profit
df.sort_values("Profit").head(10)[
    ["Category", "Sub-Category", "Sales", "Discount", "Profit"]]

             Category Sub-Category      Sales  Discount     Profit
7772       Technology     Machines   4499.985       0.7 -6599.9780
683        Technology     Machines   7999.980       0.5 -3839.9904
9774  Office Supplies      Binders   2177.584       0.8 -3701.8928
3011       Technology     Machines   2549.985       0.7 -3399.9800
4991  Office Supplies      Binders   1889.990       0.8 -2929.4845
3151       Technology     Machines   1799.994       0.7 -2639.9912
5310  Office Supplies      Binders   1525.188       0.8 -2287.7820
9639        Furniture       Tables   4297.644       0.4 -1862.3124
1199  Office Supplies      Binders   1088.792       0.8 -1850.9464
2697       Technology     Machines  22638.480       0.5 -1811.0784

In [15]:
# Check categorical frequency

categorical_cols = [
    "Ship Mode",
    "Segment",
    "Region",
    "Category",
    "Sub-Category"
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

Ship Mode
Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

Segment
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

Region
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Category
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

Sub-Category
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: count, dtype: int64

In [16]:
# Check rare categories (<1%)

for col in categorical_cols:
    proportion = df[col].value_counts(normalize=True) * 100
    rare = proportion[proportion < 1]

    print(f"\nRare categories in {col}:")
    print(rare)

Rare categories in Ship Mode:
Series([], Name: proportion, dtype: float64)

Rare categories in Segment:
Series([], Name: proportion, dtype: float64)

Rare categories in Region:
Series([], Name: proportion, dtype: float64)

Rare categories in Category:
Series([], Name: proportion, dtype: float64)

Rare categories in Sub-Category:
Sub-Category
Copiers    0.680408
Name: proportion, dtype: float64

In [17]:
# Export cleaned dataset
df.to_csv(
    "Superstore_Cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(3), str(13)
memory usage: 3.2 MB